from enum import StrEnum


class DomainEnum(StrEnum):
    """String enum whose serialized value is stable across API and persistence layers."""


class LegalState(DomainEnum):
    LEGAL = "LEGAL"
    ILLEGAL = "ILLEGAL"
    UNKNOWN = "UNKNOWN"


class FreeState(DomainEnum):
    FREE = "FREE"
    PAID = "PAID"
    UNKNOWN = "UNKNOWN"


class PhysicalState(DomainEnum):
    PARKABLE = "PARKABLE"
    NOT_PARKABLE = "NOT_PARKABLE"
    UNKNOWN = "UNKNOWN"


class SegmentSide(DomainEnum):
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    UNKNOWN = "UNKNOWN"


class EvidenceReliabilityTier(DomainEnum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"


class EvidenceStoragePolicy(DomainEnum):
    PERSIST = "PERSIST"
    EPHEMERAL = "EPHEMERAL"
    REFERENCE_ONLY = "REFERENCE_ONLY"


class EvidenceSourceType(DomainEnum):
    OFFICIAL_CODE = "OFFICIAL_CODE"
    OFFICIAL_GIS = "OFFICIAL_GIS"
    VERIFIED_SIGN = "VERIFIED_SIGN"
    UNIVERSITY = "UNIVERSITY"
    OSM = "OSM"
    COMMUNITY = "COMMUNITY"
    WEB = "WEB"
    IMAGERY_INFERENCE = "IMAGERY_INFERENCE"


class ParkingRuleType(DomainEnum):
    NO_PARKING = "NO_PARKING"
    TIME_LIMIT = "TIME_LIMIT"
    PAID = "PAID"
    PERMIT_ONLY = "PERMIT_ONLY"
    LOADING = "LOADING"
    STREET_CLEANING = "STREET_CLEANING"
    EVENT_RESTRICTION = "EVENT_RESTRICTION"
    OTHER = "OTHER"


class RegulationReasonCode(DomainEnum):
    """Stable machine-readable explanations emitted by the regulation engine."""

    ACTIVE_NO_PARKING = "ACTIVE_NO_PARKING"
    TIME_LIMIT_APPLIES = "TIME_LIMIT_APPLIES"
    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED"
    PERMIT_REQUIRED = "PERMIT_REQUIRED"
    VALID_PERMIT_EXCEPTION = "VALID_PERMIT_EXCEPTION"
    VALID_VEHICLE_EXCEPTION = "VALID_VEHICLE_EXCEPTION"
    PAYMENT_REQUIRED = "PAYMENT_REQUIRED"
    NO_PAYMENT_REQUIRED = "NO_PAYMENT_REQUIRED"
    LOADING_ONLY = "LOADING_ONLY"
    ACTIVE_STREET_CLEANING = "ACTIVE_STREET_CLEANING"
    ACTIVE_EVENT_RESTRICTION = "ACTIVE_EVENT_RESTRICTION"
    UNSUPPORTED_RULE = "UNSUPPORTED_RULE"
    INVALID_RULE_SCHEDULE = "INVALID_RULE_SCHEDULE"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    EVIDENCE_NOT_YET_AVAILABLE = "EVIDENCE_NOT_YET_AVAILABLE"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    LOWER_TIER_EVIDENCE_OVERRIDDEN = "LOWER_TIER_EVIDENCE_OVERRIDDEN"
    RULE_INACTIVE = "RULE_INACTIVE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class DayOfWeek(DomainEnum):
    MON = "MON"
    TUE = "TUE"
    WED = "WED"
    THU = "THU"
    FRI = "FRI"
    SAT = "SAT"
    SUN = "SUN"


class SearchSessionStatus(DomainEnum):
    CREATED = "CREATED"
    PLANNED = "PLANNED"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"
